package com.hib.entity;

// Generated Nov 23, 2017 11:41:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int empSeq;
	private Date createdOn;
	private String empName;
	private UserLogInf userLogInf;

	public Employee() {
	}

	public Employee(int empSeq) {
		this.empSeq = empSeq;
	}

	public Employee(int empSeq, Date createdOn, String empName,
			UserLogInf userLogInf) {
		this.empSeq = empSeq;
		this.createdOn = createdOn;
		this.empName = empName;
		this.userLogInf = userLogInf;
	}

	public int getEmpSeq() {
		return this.empSeq;
	}

	public void setEmpSeq(int empSeq) {
		this.empSeq = empSeq;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public UserLogInf getUserLogInf() {
		return this.userLogInf;
	}

	public void setUserLogInf(UserLogInf userLogInf) {
		this.userLogInf = userLogInf;
	}

}
