package com.hib.entity;

// Generated Nov 23, 2017 11:41:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserLogInf generated by hbm2java
 */
public class UserLogInf implements java.io.Serializable {

	private int userSeq;
	private Employee employee;
	private Date createdOn;
	private String userNameS;

	public UserLogInf() {
	}

	public UserLogInf(Employee employee) {
		this.employee = employee;
	}

	public UserLogInf(Employee employee, Date createdOn, String userNameS) {
		this.employee = employee;
		this.createdOn = createdOn;
		this.userNameS = userNameS;
	}

	public int getUserSeq() {
		return this.userSeq;
	}

	public void setUserSeq(int userSeq) {
		this.userSeq = userSeq;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getUserNameS() {
		return this.userNameS;
	}

	public void setUserNameS(String userNameS) {
		this.userNameS = userNameS;
	}

}
