package com.hib.entity.msdb;

// Generated Nov 30, 2017 9:55:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * UserAddress generated by hbm2java
 */
public class UserAddress implements java.io.Serializable {

	private BigDecimal userCode;
	private String street;
	private String city;
	private String state;
	private BigDecimal mobie;
	private UserInfo userInfo;

	public UserAddress() {
	}

	public UserAddress(BigDecimal userCode) {
		this.userCode = userCode;
	}

	public UserAddress(BigDecimal userCode, String street, String city,
			String state, BigDecimal mobie, UserInfo userInfo) {
		this.userCode = userCode;
		this.street = street;
		this.city = city;
		this.state = state;
		this.mobie = mobie;
		this.userInfo = userInfo;
	}

	public BigDecimal getUserCode() {
		return this.userCode;
	}

	public void setUserCode(BigDecimal userCode) {
		this.userCode = userCode;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public BigDecimal getMobie() {
		return this.mobie;
	}

	public void setMobie(BigDecimal mobie) {
		this.mobie = mobie;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

}
