package com.hib.entity.msdb;

// Generated Nov 30, 2017 9:55:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private BigDecimal userCode;
	private UserAddress userAddress;
	private String userName;
	private String userYype;
	private Set naUserAuths = new HashSet(0);

	public UserInfo() {
	}

	public UserInfo(UserAddress userAddress) {
		this.userAddress = userAddress;
	}

	public UserInfo(UserAddress userAddress, String userName, String userYype,
			Set naUserAuths) {
		this.userAddress = userAddress;
		this.userName = userName;
		this.userYype = userYype;
		this.naUserAuths = naUserAuths;
	}

	public BigDecimal getUserCode() {
		return this.userCode;
	}

	public void setUserCode(BigDecimal userCode) {
		this.userCode = userCode;
	}

	public UserAddress getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(UserAddress userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserYype() {
		return this.userYype;
	}

	public void setUserYype(String userYype) {
		this.userYype = userYype;
	}

	public Set getNaUserAuths() {
		return this.naUserAuths;
	}

	public void setNaUserAuths(Set naUserAuths) {
		this.naUserAuths = naUserAuths;
	}

}
